package common

const (
	SFDB_CONFIG_NAME        = "SFDB_CONFIG_NAME"
	SFDB_DB_PASSWORD        = "SFDB_DB_PASSWORD"
	SFDB_TELEGRAM_BOT_TOKEN = "SFDB_TELEGRAM_BOT_TOKEN"
	SFDB_ENCRYPTION_KEY     = "SFDB_ENCRYPTION_KEY"
)
