backup:
    compression:
        type: gzip
        level: best
        required: true
    encryption:
        enabled: true
    exclude:
        databases:
        user: false
        system_databases: true
        data: false
    db_list:
        file: /etc/sfDBTools/config/db_list1.txt
    mysqldump_args: -CfQq --max-allowed-packet=1G --hex-blob --order-by-primary --single-transaction --routines=true --triggers=true --opt
    retention:
        cleanup_enabled: true
        cleanup_schedule: daily
        days: 1
    output:
        base_directory: /mnt/nfs/backup
        capture_gtid: true
        create_backup_info: true
        cleanup_temp: true
        naming:
            include_client_code: true
            include_hostname: true
            pattern: '{database}_{timestamp}_{type}'
        structure:
            create_subdirs: true
            pattern: '{date}/{client}'
        temp_directory: /tmp/sfDBTools_backup
    verification:
        compare_checksums: true
        disk_space_check: true
        verify_after_write: true
config_dir:
    database_config: /etc/sfDBTools/config/db_config
    database_list: /etc/sfDBTools/config/db_list
    mariadb_config_templates: config/templates/server.cnf
general:
    app_name: sfDBTools
    author: Hadiyatna Muflihun
    client_code: dataon
    locale:
        date_format: "2006-01-02"
        time_format: "15:04:05"
        timezone: Asia/Jakarta
    version: 1.0.0
log:
    format: text # text, json
    level: debug # debug, info, warn, error, fatal
    output:
        console:
            enabled: true # true, false
        file:
            dir: /var/log/sfDBTools
            enabled: true
            filename_pattern: sfDBTools_{date}.log
            rotation:
                compress_old: true
                daily: true
                max_size: 100MB
                retention_days: 7
    timezone: Asia/Jakarta
mariadb:
    binlog_dir: /mnt/nfs/mariadb/binlogs
    config_dir: /etc/my.cnf.d/server.cnf
    data_dir: /mnt/nfs/mariadb/data
    encryption_key_file: /etc/sfDBTools/key_maria_nbc.txt
    innodb_encrypt_tables: true
    log_dir: /mnt/nfs/mariadb/logs
    port: 3306
    server_id: 1
    version: 10.6.23
system_users:
    users:
        - sst_user
        - papp
        - sysadmin
        - backup_user
        - dbaDO
        - maxscale
